// Demo prices only. Specifications are for the named regional configuration.
export const devices = [
  {
    "id": "redmagic-10-pro",
    "name": "REDMAGIC 10 Pro",
    "brand": "REDMAGIC",
    "family": "redmagic",
    "category": "phone",
    "price": 1150000,
    "chip": "Snapdragon 8 Elite",
    "display": "6.85-inch AMOLED · 2688 × 1216",
    "refresh": "144Hz",
    "battery": "7,050mAh",
    "charging": "Up to 100W wired",
    "memory": "12GB / 256GB",
    "region": "Global",
    "source": "https://global.redmagic.gg/pages/redmagic-10-pro-specs",
    "color": "#b4b7a5",
    "cameras": "redmagic",
    "tag": "BUILT FOR RANKED",
    "description": "An uninterrupted display, active cooling and dedicated shoulder triggers. Built around the way you play."
  },
  {
    "id": "redmagic-9-pro",
    "name": "REDMAGIC 9 Pro",
    "brand": "REDMAGIC",
    "family": "redmagic",
    "category": "phone",
    "price": 850000,
    "chip": "Snapdragon 8 Gen 3",
    "display": "6.8-inch AMOLED · 2480 × 1116",
    "refresh": "120Hz",
    "battery": "6,500mAh",
    "charging": "80W wired",
    "memory": "12GB / 256GB",
    "region": "Global",
    "source": "https://global.redmagic.gg/pages/redmagic-9-pro-specs",
    "color": "#414441",
    "cameras": "redmagic",
    "tag": "PURE PERFORMANCE",
    "description": "A flat, full-screen gaming phone with ICE 13 cooling and responsive shoulder controls."
  },
  {
    "id": "redmagic-astra",
    "name": "REDMAGIC Astra",
    "brand": "REDMAGIC",
    "family": "redmagic",
    "category": "tablet",
    "price": 990000,
    "chip": "Snapdragon 8 Elite",
    "display": "9.06-inch OLED · 2400 × 1504",
    "refresh": "165Hz",
    "battery": "8,200mAh",
    "charging": "Fast charging supported",
    "memory": "12GB / 256GB",
    "region": "Global",
    "source": "https://global.redmagic.gg/pages/redmagic-astra-gaming-tablet-specs",
    "color": "#777e75",
    "cameras": "astra",
    "tag": "SMALL SIZE. BIG GAME.",
    "description": "A compact OLED gaming tablet with active cooling and a generous screen for your next session."
  },
  {
    "id": "redmagic-nova",
    "name": "REDMAGIC Nova",
    "brand": "REDMAGIC",
    "family": "redmagic",
    "category": "tablet",
    "price": 880000,
    "chip": "Snapdragon 8 Gen 3 Leading Version",
    "display": "10.9-inch LCD · 2880 × 1800",
    "refresh": "144Hz",
    "battery": "10,100mAh",
    "charging": "80W wired",
    "memory": "12GB / 256GB",
    "region": "Global",
    "source": "https://global.redmagic.gg/pages/redmagic-nova-gaming-tablet-specs",
    "color": "#5a6160",
    "cameras": "nova",
    "tag": "GO BIG",
    "description": "A larger gaming canvas with a built-in cooling fan, four speakers and a substantial battery."
  },
  {
    "id": "iqoo-13",
    "name": "iQOO 13",
    "brand": "iQOO",
    "family": "iqoo",
    "category": "phone",
    "price": 1050000,
    "chip": "Snapdragon 8 Elite",
    "display": "6.82-inch AMOLED · 3168 × 1440",
    "refresh": "144Hz",
    "battery": "6,000mAh",
    "charging": "120W wired",
    "memory": "12GB / 256GB",
    "region": "India version",
    "source": "https://www.iqoo.com/in/products/param/iqoo13",
    "color": "#e4e0d6",
    "cameras": "iqoo",
    "tag": "FAST BY DESIGN",
    "description": "Flagship performance, a sharp 2K display and fast charging. A versatile choice for play and everyday use."
  },
  {
    "id": "iqoo-12",
    "name": "iQOO 12",
    "brand": "iQOO",
    "family": "iqoo",
    "category": "phone",
    "price": 780000,
    "chip": "Snapdragon 8 Gen 3",
    "display": "6.78-inch AMOLED · 2800 × 1260",
    "refresh": "144Hz",
    "battery": "5,000mAh",
    "charging": "120W wired",
    "memory": "12GB / 256GB",
    "region": "India version",
    "source": "https://www.iqoo.com/in/products/param/iqoo12",
    "color": "#cec9bb",
    "cameras": "iqoo",
    "tag": "ALL-ROUND POWER",
    "description": "High-end processing and a bright AMOLED display in a clean, understated body."
  },
  {
    "id": "oneplus-13",
    "name": "OnePlus 13",
    "brand": "OnePlus",
    "family": "oneplus",
    "category": "phone",
    "price": 1200000,
    "chip": "Snapdragon 8 Elite",
    "display": "6.82-inch LTPO AMOLED · 3168 × 1440",
    "refresh": "120Hz",
    "battery": "6,000mAh",
    "charging": "100W wired / 50W wireless",
    "memory": "12GB / 256GB",
    "region": "Global",
    "source": "https://www.oneplus.com/global/13/specs",
    "color": "#c8d2d4",
    "cameras": "round",
    "tag": "POWER MEETS POLISH",
    "description": "A premium daily driver with flagship gaming performance, a large battery and versatile cameras."
  },
  {
    "id": "oneplus-12",
    "name": "OnePlus 12",
    "brand": "OnePlus",
    "family": "oneplus",
    "category": "phone",
    "price": 920000,
    "chip": "Snapdragon 8 Gen 3",
    "display": "6.82-inch LTPO AMOLED · 3168 × 1440",
    "refresh": "120Hz",
    "battery": "5,400mAh",
    "charging": "100W wired / 50W wireless",
    "memory": "12GB / 256GB",
    "region": "Global",
    "source": "https://www.oneplus.com/global/12/specs",
    "color": "#47766d",
    "cameras": "round",
    "tag": "A FLAGSHIP CLASSIC",
    "description": "A spacious display, balanced performance and fast charging for the game and everything after it."
  },
  {
    "id": "oneplus-ace-5",
    "name": "OnePlus Ace 5",
    "brand": "OnePlus",
    "family": "ace",
    "category": "phone",
    "price": 690000,
    "chip": "Snapdragon 8 Gen 3",
    "display": "6.78-inch display · 2780 × 1264",
    "refresh": "120Hz",
    "battery": "6,415mAh",
    "charging": "80W wired",
    "memory": "12GB / 256GB",
    "region": "China version",
    "source": "https://www.oneplus.com/cn/ace-5/specs",
    "color": "#b1c4a8",
    "cameras": "round",
    "tag": "THE ACE UP YOUR SLEEVE",
    "description": "A flat-screen performance phone with a large battery. This demo uses the China-market specification."
  },
  {
    "id": "oneplus-ace-5-pro",
    "name": "OnePlus Ace 5 Pro",
    "brand": "OnePlus",
    "family": "ace",
    "category": "phone",
    "price": 890000,
    "chip": "Snapdragon 8 Elite",
    "display": "6.78-inch display · 2780 × 1264",
    "refresh": "120Hz",
    "battery": "6,100mAh",
    "charging": "100W wired",
    "memory": "12GB / 256GB",
    "region": "China version",
    "source": "https://www.oneplus.com/cn/ace-5-pro/specs",
    "color": "#62526c",
    "cameras": "round",
    "tag": "RAISE YOUR GAME",
    "description": "A performance-focused Ace with Snapdragon 8 Elite power. China-market specification shown."
  },
  {
    "id": "legion-tab-gen-3",
    "name": "Legion Tab Gen 3",
    "brand": "Lenovo Legion",
    "family": "legion",
    "category": "tablet",
    "price": 820000,
    "chip": "Snapdragon 8 Gen 3",
    "display": "8.8-inch LCD · 2560 × 1600",
    "refresh": "165Hz",
    "battery": "6,550mAh",
    "charging": "USB-C Power Delivery",
    "memory": "12GB / 256GB",
    "region": "Global",
    "source": "https://psref.lenovo.com/syspool/Sys/PDF/Lenovo_Tablets/Legion_Tab_8.8_3/Legion_Tab_8.8_3_Spec.html",
    "color": "#4a515a",
    "cameras": "legion",
    "tag": "POCKET-SIZED POWER",
    "description": "A compact gaming tablet with dual USB-C ports, Coldfront cooling and a fast 165Hz display."
  },
  {
    "id": "legion-tab-gen-2",
    "name": "Legion Tab (8+ Gen 1)",
    "brand": "Lenovo Legion",
    "family": "legion",
    "category": "tablet",
    "price": 590000,
    "chip": "Snapdragon 8+ Gen 1",
    "display": "8.8-inch LCD · 2560 × 1600",
    "refresh": "144Hz",
    "battery": "6,550mAh",
    "charging": "USB-C Power Delivery",
    "memory": "12GB / 256GB",
    "region": "Global Legion Tab / Gen 2",
    "source": "https://psref.lenovo.com/syspool/Sys/PDF/Lenovo_Tablets/Legion_Tab/Legion_Tab_Spec.PDF",
    "color": "#9ba3a2",
    "cameras": "legion",
    "tag": "COMPACT. CAPABLE.",
    "description": "A lightweight 8.8-inch tablet with stereo speakers, expandable storage and a comfortable gaming footprint."
  }
];
export const money = value => new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(value);
