import assert from 'node:assert/strict';
import fs from 'node:fs';
import {devices as seed} from '../devices-data.js';
import {cleanDevice,safeImage,safeLink} from '../device-utils.js';
import {normalizeCart,cartSummary} from '../cart-state.js';
import {answerQuestion} from '../assistant-core.js';
const storage=()=>{const map=new Map();return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,String(v)),removeItem:k=>map.delete(k)};};
globalThis.localStorage=storage();globalThis.sessionStorage=storage();
const {readDevices,saveDevice,enterPreview,employee,signOut,resetPreview}=await import('../store.js');
assert.equal(seed.length,32);assert.equal(new Set(seed.map(d=>d.id)).size,32);
for(const d of seed){cleanDevice(d);assert.ok(fs.existsSync(new URL('../'+d.image,import.meta.url)),d.image);}
assert.equal(safeImage('javascript:alert(1)'), '');assert.equal(safeImage('data:image/svg+xml,<svg/>',true),'');assert.equal(safeLink('https://user:password@example.com'),'');
assert.throws(()=>cleanDevice({...seed[0],price:-1}));assert.throws(()=>cleanDevice({...seed[0],id:'../bad'}));
assert.deepEqual(normalizeCart([{id:seed[0].id,quantity:2},{id:seed[0].id,quantity:120},{id:'bad',quantity:-3}]),[{id:seed[0].id,quantity:99}]);
assert.equal(cartSummary([{id:seed[0].id,quantity:2,price:1}],seed)[0].device.price,seed[0].price);
assert.equal(answerQuestion('How much is the REDMAGIC 10 Pro?',seed).refer,false);
assert.equal(answerQuestion('Does REDMAGIC 10 Pro do 120fps in CODM?',seed).refer,true);
assert.equal(answerQuestion('Is the OnePlus 13 waterproof?',seed).refer,true);
assert.equal(answerQuestion('What about delivery?',seed).refer,true);
assert.match(answerQuestion('RAM vs storage?',seed).text,/Virtual RAM/);
assert.match(answerQuestion('What is refresh rate?',seed).text,/does not guarantee/);
assert.match(answerQuestion('How does fast charging work?',seed).text,/charging protocol/);
assert.equal(answerQuestion('What FPS does the OnePlus 13 get in CODM?',seed).refer,true);
assert.deepEqual(answerQuestion('iQOO 13 vs OnePlus 13',seed).ids.sort(),['iqoo-13','oneplus-13']);
assert.deepEqual(answerQuestion('Red Magic 10 Pro battery',seed).ids,['redmagic-10-pro']);
assert.ok(answerQuestion('show infinix phones',seed).ids.every(id=>id.startsWith('infinix')));
assert.ok(answerQuestion('Phones under ₦550k',seed).ids.every(id=>seed.find(d=>d.id===id).price<=550000));
assert.equal(answerQuestion('What charging does the REDMAGIC 10S Pro use?',seed).ids.length,1);
assert.equal(await employee(),null);await assert.rejects(saveDevice({...seed[0],price:100},null,false),/Employee access/);
enterPreview();assert.ok((await employee()).preview);
const saved=await saveDevice({...seed[0],price:1111111},null,false);
assert.equal((await readDevices()).find(d=>d.id===saved.id).price,1111111);
await assert.rejects(saveDevice({...seed[0],price:2222222},null,false),/changed/);
await saveDevice({...saved,status:'draft'},saved._version,false);
assert.equal((await readDevices()).length,31);assert.equal((await readDevices(true)).length,32);
await assert.rejects(saveDevice({...seed[0]},null,true),/already in use/);
await saveDevice({...seed[0],id:'new-demo-device',name:'New demo device',status:'published'},null,true);
assert.equal((await readDevices()).length,32);assert.equal((await readDevices(true)).length,33);
resetPreview();assert.equal((await readDevices()).length,32);await signOut();assert.equal(await employee(),null);
console.log('PASS: 32 catalogue photos, input validation, catalogue answers, cart pricing, employee gate, edit/add/publish/draft, conflicting edits, reset/sign-out.');
