import {fileURLToPath} from 'node:url';
import {PGlite} from '@electric-sql/pglite';import fs from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();const root=fileURLToPath(new URL('../',import.meta.url));
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create schema storage; create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,public,storage to anon,authenticated,service_role; grant execute on function auth.uid() to anon,authenticated;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid,bucket_id text,name text);alter table storage.objects enable row level security;
grant select,insert,update,delete on storage.objects to anon,authenticated;
insert into auth.users values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');`);
for(const f of ['001_catalogue.sql','002_seed_devices.sql','003_assistant_budget.sql'])await db.exec(fs.readFileSync(root+'supabase/migrations/'+f,'utf8'));
await db.exec(`insert into public.employees(user_id) values('11111111-1111-4111-8111-111111111111');update public.devices set status='draft' where id='redmagic-10-pro';set role anon;`);
assert.equal((await db.query('select count(*)::int as n from public.devices')).rows[0].n,31);
await assert.rejects(db.exec(`update public.devices set status='draft' where id='iqoo-13'`));
await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',false);`);
assert.equal((await db.query('select count(*)::int as n from public.devices')).rows[0].n,31);
assert.equal((await db.query(`update public.devices set status='draft' where id='iqoo-13' returning id`)).rows.length,0);
await assert.rejects(db.exec(`insert into public.employees(user_id) values('22222222-2222-4222-8222-222222222222')`));
await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('device-images','unauthorized.webp')`));
await db.exec(`select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',false);`);
assert.equal((await db.query('select count(*)::int as n from public.devices')).rows[0].n,32);
assert.equal((await db.query(`update public.devices set status='published' where id='redmagic-10-pro' returning id`)).rows.length,1);
await db.exec(`insert into storage.objects(bucket_id,name) values('device-images','approved.webp')`);
await assert.rejects(db.exec(`select public.consume_assistant_budget('11111111-1111-4111-8111-111111111111')`));
await db.exec(`reset role;delete from public.employees;set role authenticated;`);
assert.equal((await db.query(`update public.devices set status='draft' where id='iqoo-13' returning id`)).rows.length,0);
await db.exec(`reset role;set role service_role;`);
for(let n=0;n<30;n++)assert.equal((await db.query(`select public.consume_assistant_budget('11111111-1111-4111-8111-111111111111') as allowed`)).rows[0].allowed,true);
assert.equal((await db.query(`select public.consume_assistant_budget('11111111-1111-4111-8111-111111111111') as allowed`)).rows[0].allowed,false);
console.log('PASS: migrations/32 seeds; anonymous, customer, staff and revoked staff RLS; storage authorization; employee self-promotion denied; AI budget/service-only RPC. Auth/storage schemas were stubbed in local PGlite.');await db.close();
